# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2e81fe4e602faad4be0ea61271e9a10242c5a6d565d1757d53e1cae1dba6f255fd7af15b2eef13430618f7d065b63ba38123ba5841fecf1c3ff02caafc7e9ca

test:
  secret_key_base: ad60833582ffa2b85becf232e8d38acfcd7cad64eb518dbdbcc93fbfaf9ca6c5b6a2d230c32e82deb645eb2b7ff64db4afab7a61a360472925b22680fe85929d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
